# Generated by Django 4.1.5 on 2023-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('image', models.CharField(max_length=200)),
                ('cocktail_uid', models.CharField(default='None', max_length=200)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('drinkName', models.CharField(default='', max_length=200)),
                ('instructions', models.TextField()),
                ('ingredient1', models.CharField(default='', max_length=200)),
                ('ingredient2', models.CharField(default='', max_length=200)),
                ('ingredient3', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('glass', models.CharField(default='', max_length=200)),
                ('ingredient4', models.CharField(default='', max_length=200, null=True)),
                ('ingredient5', models.CharField(default='', max_length=200, null=True)),
                ('ingredient6', models.CharField(default='', max_length=200, null=True)),
                ('ingredient7', models.CharField(default='', max_length=200, null=True)),
                ('ingredient8', models.CharField(default='', max_length=200, null=True)),
                ('ingredient9', models.CharField(default='', max_length=200, null=True)),
                ('ingredient10', models.CharField(default='None', max_length=200, null=True)),
                ('ingredient11', models.CharField(default='None', max_length=200, null=True)),
                ('ingredient12', models.CharField(default='None', max_length=200, null=True)),
                ('ingredient13', models.CharField(default='None', max_length=200, null=True)),
                ('ingredient14', models.CharField(default='None', max_length=200, null=True)),
                ('ingredient15', models.CharField(default='None', max_length=200, null=True)),
                ('measure1', models.CharField(default='None', max_length=200, null=True)),
                ('measure2', models.CharField(default='None', max_length=200, null=True)),
                ('measure3', models.CharField(default='None', max_length=200, null=True)),
                ('measure4', models.CharField(default='None', max_length=200, null=True)),
                ('measure5', models.CharField(default='None', max_length=200, null=True)),
                ('measure6', models.CharField(default='None', max_length=200, null=True)),
                ('measure7', models.CharField(default='None', max_length=200, null=True)),
                ('measure8', models.CharField(default='None', max_length=200, null=True)),
                ('measure9', models.CharField(default='None', max_length=200, null=True)),
                ('measure10', models.CharField(default='None', max_length=200, null=True)),
                ('measure11', models.CharField(default='None', max_length=200, null=True)),
                ('measure12', models.CharField(default='None', max_length=200, null=True)),
                ('measure13', models.CharField(default='None', max_length=200, null=True)),
                ('measure14', models.CharField(default='None', max_length=200, null=True)),
                ('measure15', models.CharField(default='None', max_length=200, null=True)),
                ('alcoholic', models.CharField(default='None', max_length=200, null=True)),
            ],
        ),
    ]
