# Generated by Django 4.1.5 on 2023-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='id',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail',
            field=models.CharField(default='1239482', max_length=200, primary_key=True, serialize=False),
        ),
    ]
