# Generated by Django 4.1.5 on 2023-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0002_remove_cocktail_id_alter_cocktail_cocktail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='cocktail',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='cocktail_uid',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='id',
            field=models.AutoField(default=318301313585762041810, editable=False, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
