# Generated by Django 4.1.5 on 2023-04-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0003_alter_cocktail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='cocktail_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
