# Generated by Django 4.1.5 on 2023-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0003_remove_cocktail_cocktail_cocktail_cocktail_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
