# Generated by Django 4.1.5 on 2023-04-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0004_cocktail_cocktail_id_alter_cocktail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_id',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
