# Generated by Django 4.1.5 on 2023-04-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0005_alter_cocktail_cocktail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
