# Generated by Django 4.1.5 on 2023-04-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0008_userprofile_bookmarked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bookmarked_at',
        ),
    ]
